# https://console.cloud.google.com/artifacts/docker/gemini-code-dev/us/gemini-cli/sandbox
FROM us-docker.pkg.dev/gemini-code-dev/gemini-cli/sandbox:0.12.0-nightly.20251023.c4c0c0d1

USER root

RUN apt-get update && \
    apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LO https://go.dev/dl/go1.24.0.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.24.0.linux-amd64.tar.gz && \
    rm go1.24.0.linux-amd64.tar.gz

RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    mv /root/.local/bin/uv /usr/local/bin/uv

ARG CACHEBUST

# COPY ./beads /tmp/beads
# RUN cd /tmp/beads && \
#     /usr/local/go/bin/go build -o /usr/local/bin/bd ./cmd/bd && \
#     rm -rf /tmp/beads

RUN git clone https://github.com/steveyegge/beads /tmp/beads && \
    cd /tmp/beads && \
    /usr/local/go/bin/go build -o /usr/local/bin/bd ./cmd/bd && \
    cd / && \
    rm -rf /tmp/beads

RUN mv /usr/local/bin/bd /usr/local/bin/bd-original && \
    echo '#!/bin/sh\nbd-original --no-daemon "$@"' > /usr/local/bin/bd && \
    chmod +x /usr/local/bin/bd

USER 1000

RUN bd version

WORKDIR /home/node/dev
