(kbd-map
 (:mode in-math?)

 ;; (from https://github.com/hammerfunctor/dotfiles)
 ;; bold-up char to denote vectors
 ;; 65 - 90
 ("v v A" (insert "<b-up-A>"))
 ("v v B" (insert "<b-up-B>"))
 ("v v C" (insert "<b-up-C>"))
 ("v v D" (insert "<b-up-D>"))
 ("v v E" (insert "<b-up-E>"))
 ("v v F" (insert "<b-up-F>"))
 ("v v G" (insert "<b-up-G>"))
 ("v v H" (insert "<b-up-H>"))
 ("v v I" (insert "<b-up-I>"))
 ("v v J" (insert "<b-up-J>"))
 ("v v K" (insert "<b-up-K>"))
 ("v v L" (insert "<b-up-L>"))
 ("v v M" (insert "<b-up-M>"))
 ("v v N" (insert "<b-up-N>"))
 ("v v O" (insert "<b-up-O>"))
 ("v v P" (insert "<b-up-P>"))
 ("v v Q" (insert "<b-up-Q>"))
 ("v v R" (insert "<b-up-R>"))
 ("v v S" (insert "<b-up-S>"))
 ("v v T" (insert "<b-up-T>"))
 ("v v U" (insert "<b-up-U>"))
 ("v v V" (insert "<b-up-V>"))
 ("v v W" (insert "<b-up-W>"))
 ("v v X" (insert "<b-up-X>"))
 ("v v Y" (insert "<b-up-Y>"))
 ("v v Z" (insert "<b-up-Z>"))

 ;; 97 - 122
 ("v v a" (insert "<b-up-a>"))
 ("v v b" (insert "<b-up-b>"))
 ("v v c" (insert "<b-up-c>"))
 ("v v d" (insert "<b-up-d>"))
 ("v v e" (insert "<b-up-e>"))
 ("v v f" (insert "<b-up-f>"))
 ("v v g" (insert "<b-up-g>"))
 ("v v h" (insert "<b-up-h>"))
 ("v v i" (insert "<b-up-i>"))
 ("v v j" (insert "<b-up-j>"))
 ("v v k" (insert "<b-up-k>"))
 ("v v l" (insert "<b-up-l>"))
 ("v v m" (insert "<b-up-m>"))
 ("v v n" (insert "<b-up-n>"))
 ("v v o" (insert "<b-up-o>"))
 ("v v p" (insert "<b-up-p>"))
 ("v v q" (insert "<b-up-q>"))
 ("v v r" (insert "<b-up-r>"))
 ("v v s" (insert "<b-up-s>"))
 ("v v t" (insert "<b-up-t>"))
 ("v v u" (insert "<b-up-u>"))
 ("v v v" (insert "<b-up-v>"))
 ("v v w" (insert "<b-up-w>"))
 ("v v x" (insert "<b-up-x>"))
 ("v v y" (insert "<b-up-y>"))
 ("v v z" (insert "<b-up-z>"))

 )
