= README

I use https://github.com/altdesktop/i3ipc-python to create workspaces.

Here are some resources about i3 workspace management:
* https://github.com/swaywm/sway/pull/3022
* https://github.com/swaywm/sway/issues/1005

== TODO: Rework workspace scripts

As of now I have my workspace scripts as executables on my path, and they assume that my i3init
library is available.
I ensure that it is available by installing it in a global virtual environmen ($HOME/.venv) and
activating the environment on login.
Then I can launch the workspace scripts from anywhere.

I don't like the automatic activation of a virtual environment.
Easy to forget how and why it's done.

I think a better approach would be to execute the python from the virtual environment explicitly
each time I want to launch a workspace script.
Seems it would necessitate some wrapper for each workspace script - I don't see another way to make
all workspace scripts easily available, as they are now (now they are just executables on PATH).

I could create one python script for all workspaces, then I would need only one wrapper for calling
the script with the virtual environment python.
Inside the script I can select what I want, probably with https://github.com/bcbnz/python-rofi.
