require ('reinis.options')
require ('reinis.colors')
require ('reinis.filetype')
require ('reinis.remaps')
require ('reinis.lspconfig')
require ('reinis.neorg')
require ('reinis.treesitter')
require ('reinis.treesitter-context')
require ('reinis.cmp')

-- require ('reinis.copilot')
