require("reinis.editing")
require("reinis.colors")
require("reinis.lspconfig")
require("reinis.neorg")
require("reinis.treesitter")
require("reinis.treesitter-context")
require("reinis.cmp")
-- require("reinis.copilot")
require("reinis.llm")
