# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot.initrd.availableKernelModules = ["ahci" "ohci_pci" "ehci_pci" "xhci_pci" "firewire_ohci" "usb_storage" "sd_mod"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3c5b0708-454c-49ef-8e87-a5d86c6dcec9";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/baea55f9-058a-45dd-833c-c1956f5098f2";}
  ];

  nix.maxJobs = lib.mkDefault 3;
}
