from enum import Enum

class Event(Enum):
    """An enumeration of events that can be subscribed to with
    :func:`Connection.on()`.
    """
    WORKSPACE = ...
    OUTPUT = ...
    MODE = ...
    WINDOW = ...
    BARCONFIG_UPDATE = ...
    BINDING = ...
    SHUTDOWN = ...
    TICK = ...
    INPUT = ...
    WORKSPACE_FOCUS = ...
    WORKSPACE_INIT = ...
    WORKSPACE_EMPTY = ...
    WORKSPACE_URGENT = ...
    WORKSPACE_RELOAD = ...
    WORKSPACE_RENAME = ...
    WORKSPACE_RESTORED = ...
    WORKSPACE_MOVE = ...
    WINDOW_NEW = ...
    WINDOW_CLOSE = ...
    WINDOW_FOCUS = ...
    WINDOW_TITLE = ...
    WINDOW_FULLSCREEN_MODE = ...
    WINDOW_MOVE = ...
    WINDOW_FLOATING = ...
    WINDOW_URGENT = ...
    WINDOW_MARK = ...
    SHUTDOWN_RESTART = ...
    SHUTDOWN_EXIT = ...
    INPUT_ADDED = ...
    INPUT_REMOVED = ...
