# https://starship.rs/config/

[git_commit]
tag_symbol = " tag "
format = "[git: \\($hash$tag\\)]($style) "
style = "bold purple"

[git_branch]
symbol = ""
format = "[git: $branch(:$remote_branch)]($style) "
only_attached = true

[sudo]
style = "bold blue"
disabled = false
format = "[sudo]($style)"

[jobs]
number_threshold = 1
format = '[\[+$number\]]($style) '

[python]
# version_format = "${major}.${minor}.${micro}"
format = '[python: ${pyenv_prefix}(${version} )(\(venv: $virtualenv\) )]($style)'

[kubernetes]
format = '[k8s: (user\[$user\] )(cluster\[$cluster\] )context\[$context\] namespace\[$namespace\]](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"
